[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "waybar-mediaplayer"
version = "1"
dependencies = [ "pygobject" ]

[project.scripts]
waybar-mediaplayer = "main:main"
